pipeline {
    agent {
        docker {
            image 'maven-com-java' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}
